# Generated by Django 5.1.2 on 2024-11-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(default='image.jpg', upload_to='photo'),
        ),
    ]
