# Generated by Django 5.1.2 on 2024-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('students', models.CharField(max_length=255)),
                ('photo', models.ImageField(default='image.jpg', upload_to='photo')),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='backend.course'),
        ),
    ]
