# Generated by Django 5.1.2 on 2024-11-17 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_course_studentprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='jobdescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
