# Generated by Django 5.1.2 on 2024-11-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_studentprofile_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
