# Generated by Django 5.1.2 on 2024-11-17 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_course_photo_alter_studentprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
